//-- Import collection publication modules (server-side)

import './users.js'
import './training-modules.js'
import './training-module-pages.js'
import './training-module-images.js'
import './training-module-videos.js'
import './training-module-audios.js'
import './training-module-documents.js'
import './training-module-templates.js'
import './training-module-settings.js'
import './training-module-user-stats.js'
import './training-module-quizzes.js'
import './training-module-questions.js'
import './training-module-answers.js'
import './training-module-scores.js'
import './training-module-surveys.js'
import './training-module-survey-questions.js'
import './training-module-survey-answers.js'
import './training-module-survey-data.js'
import './training-module-users.js'
import './clients.js'
import './training-module-user-quizzes.js'

import './training-status-summary.js'
